Id: Git.Git
Publisher: Git
Name: Git
Version: 2.30.0.2
License: GNU General Public License, version 2
InstallerType: EXE
LicenseUrl: https://github.com/git-for-windows/git/blob/master/COPYING
AppMoniker: 
Tags: git,git-scm,windows
Description: Git version control system.
Homepage: https://git-scm.com/
Installers:
  - Arch: x64
    InstallerType: INNO
    Url: https://github.com/git-for-windows/git/releases/download/v2.30.0.windows.2/Git-2.30.0.2-64-bit.exe
    Sha256: 895B93AB5230CF15D9F7A268285767C52A452D5B4332A889D9B18EB62C2C0DFE
    Language: en-US
    Switches:
      Silent: /VERYSILENT
      SilentWithProgress: /SILENT
